CREATE TABLE accepted_loans (
    id INTEGER PRIMARY KEY,
    member_id REAL,
    loan_amnt REAL,
    funded_amnt REAL,
    funded_amnt_inv REAL,
    term TEXT,
    int_rate REAL,
    installment REAL,
    grade TEXT,
    sub_grade TEXT,
    emp_title TEXT,
    emp_length TEXT,
    home_ownership TEXT,
    annual_inc REAL,
    verification_status TEXT,
    issue_d TEXT,
    pymnt_plan TEXT,
    desc TEXT,
    purpose TEXT,
    title TEXT,
    dti TEXT,
    earliest_cr_line TEXT,  -- Probablement une date, donc mettre en TEXT
    open_acc TEXT,
    pub_rec TEXT,
    revol_bal REAL,
    revol_util REAL,
    total_acc TEXT,  -- Passer en TEXT pour éviter les erreurs
    initial_list_status TEXT,
    application_type TEXT,
    pub_rec_bankruptcies INTEGER,
    mort_acc INTEGER,
    addr_state TEXT,
    hardship_flag TEXT,
    hardship_type TEXT,
    hardship_reason TEXT,
    hardship_status TEXT,
    deferral_term INTEGER,
    hardship_amount TEXT,
    hardship_start_date TEXT,
    hardship_end_date TEXT,
    payment_plan_start_date TEXT,
    hardship_length INTEGER,
    hardship_dpd INTEGER,
    hardship_loan_status TEXT,
    orig_projected_additional_accrued_interest REAL,
    hardship_payoff_balance_amount REAL,
    hardship_last_payment_amount REAL,
    disbursement_method TEXT,
    debt_settlement_flag TEXT,
    debt_settlement_flag_date TEXT,
    settlement_status TEXT,
    settlement_date TEXT,
    settlement_amount REAL,
    settlement_percentage REAL,
    settlement_term REAL
);